services:
  - type: web
    name: vintage-searcher
    runtime: node
    plan: free
    buildCommand: npm install && npm run db:generate
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prod.db
